# BuildRive.cmake
#
# Drives rive-runtime's premake/gmake2/msbuild build from CMake and exposes
# the resulting static libraries + headers as the `rive` INTERFACE target.
#
# Why premake: rive-runtime is built with premake5, not CMake. Rather than
# porting ~hundreds of sources to our CMakeLists, we invoke upstream's own
# build script (build/build_rive.sh on macOS/Linux, build_rive.ps1 on
# Windows). The script self-bootstraps premake5 on first run. Expect the
# first configure to spend 30-60s on that; subsequent configures are fast
# because premake's output is cached.
#
# Build scope:
#   - Core `rive` static lib and its in-tree deps (harfbuzz, sheenbidi,
#     yoga, miniaudio).
#   - Text + layout enabled via premake's default `--with_rive_text
#     --with_rive_layout`.
#   - GPU renderer (`rive_pls_renderer`) is NOT built here — this spike
#     renders via QPainter. That's a follow-up.
#
# Consumer usage:
#   target_link_libraries(<target> PRIVATE rive)

# Resolve paths relative to this module's directory so consumer projects
# adding us via add_subdirectory still find the submodule correctly —
# CMAKE_SOURCE_DIR would point at the host's top-level in that case.
get_filename_component(_rive_qt_plugin_dir "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
set(RIVE_RUNTIME_DIR "${_rive_qt_plugin_dir}/third_party/rive-runtime")
set(RIVE_BUILD_DIR "${CMAKE_BINARY_DIR}/rive-build")

# Release only for now. Debug doubles library sizes and the perf hit of a
# debug rive build isn't worth it during development — the spike target is
# "frame on screen", not "step through rive internals".
set(RIVE_CONFIG "release")
set(RIVE_OUT_DIR "${RIVE_BUILD_DIR}/out/${RIVE_CONFIG}")

# Generated wrapper premake file. build_rive.sh expects a premake5.lua in
# the working directory; upstream's root has premake5_v2.lua instead. The
# wrapper just resolves the submodule path and dofiles into upstream.
set(RIVE_PREMAKE_WRAPPER "${RIVE_BUILD_DIR}/premake5.lua")

file(MAKE_DIRECTORY "${RIVE_BUILD_DIR}")
file(WRITE "${RIVE_PREMAKE_WRAPPER}"
"-- Auto-generated by cmake/BuildRive.cmake — do not edit.\n"
"RIVE_RUNTIME_DIR = '${RIVE_RUNTIME_DIR}'\n"
"dofile(RIVE_RUNTIME_DIR .. '/build/rive_build_config.lua')\n"
"dofile(RIVE_RUNTIME_DIR .. '/premake5_v2.lua')\n")

# Static libs produced by the rive build that we consume.
# Note: libluau_vm.a is a stub (scripting disabled) — not linked.
if(WIN32)
    set(_rive_lib_prefix "")
    set(_rive_lib_suffix ".lib")
else()
    set(_rive_lib_prefix "lib")
    set(_rive_lib_suffix ".a")
endif()

set(RIVE_CORE_LIB   "${RIVE_OUT_DIR}/${_rive_lib_prefix}rive${_rive_lib_suffix}")
set(RIVE_HARFBUZZ   "${RIVE_OUT_DIR}/${_rive_lib_prefix}rive_harfbuzz${_rive_lib_suffix}")
set(RIVE_SHEENBIDI  "${RIVE_OUT_DIR}/${_rive_lib_prefix}rive_sheenbidi${_rive_lib_suffix}")
set(RIVE_YOGA       "${RIVE_OUT_DIR}/${_rive_lib_prefix}rive_yoga${_rive_lib_suffix}")
set(RIVE_MINIAUDIO  "${RIVE_OUT_DIR}/${_rive_lib_prefix}miniaudio${_rive_lib_suffix}")

set(RIVE_ALL_LIBS
    "${RIVE_CORE_LIB}"
    "${RIVE_HARFBUZZ}"
    "${RIVE_SHEENBIDI}"
    "${RIVE_YOGA}"
    "${RIVE_MINIAUDIO}"
)

# Wrapper script. Two reasons we need one:
#
# 1. ninja pre-creates the parent directory of any custom-command OUTPUT, so
#    by the time build_rive.sh runs, "out/release/" already exists. Upstream's
#    script treats a pre-existing OUT dir as an incremental build and fails
#    when its marker file `.rive_premake_args` is missing. Solution: drop the
#    dir if the marker is absent, then delegate.
#
# 2. On macOS we scrub the PATH of Anaconda/homebrew toolchain shims —
#    observed `warning: /opt/homebrew/anaconda3/bin/arm64-apple-darwin20.0.0-ranlib`
#    corrupting librive.a's symbol table. Xcode's clang/ar/ranlib will be
#    found via /usr/bin / CommandLineTools.
set(RIVE_BUILD_WRAPPER "${RIVE_BUILD_DIR}/build_rive_wrapper.sh")
file(WRITE "${RIVE_BUILD_WRAPPER}"
"#!/bin/bash\n"
"# Auto-generated by cmake/BuildRive.cmake — do not edit.\n"
"set -e\n"
"cd \"${RIVE_BUILD_DIR}\"\n"
"RIVE_OUT=\"out/${RIVE_CONFIG}\"\n"
"if [ -d \"$RIVE_OUT\" ] && [ ! -f \"$RIVE_OUT/.rive_premake_args\" ]; then\n"
"    rm -rf \"$RIVE_OUT\"\n"
"fi\n"
"exec \"${RIVE_RUNTIME_DIR}/build/build_rive.sh\" \"${RIVE_CONFIG}\"\n")
execute_process(COMMAND chmod +x "${RIVE_BUILD_WRAPPER}")

if(APPLE)
    set(RIVE_BUILD_CMD
        "${CMAKE_COMMAND}" -E env
        "PATH=/usr/bin:/bin:/usr/sbin:/sbin:/Library/Developer/CommandLineTools/usr/bin"
        "${RIVE_BUILD_WRAPPER}"
    )
elseif(WIN32)
    # PowerShell script shells out to premake + msbuild. Same self-bootstrap.
    # Windows equivalent of the dir-collision workaround is baked in here.
    set(RIVE_BUILD_CMD
        powershell -ExecutionPolicy Bypass -Command
        "Set-Location '${RIVE_BUILD_DIR}';"
        " if ((Test-Path 'out/${RIVE_CONFIG}') -and -not (Test-Path 'out/${RIVE_CONFIG}/.rive_premake_args'))"
        " { Remove-Item -Recurse -Force 'out/${RIVE_CONFIG}' };"
        " & '${RIVE_RUNTIME_DIR}/build/build_rive.ps1' '${RIVE_CONFIG}'"
    )
else()
    set(RIVE_BUILD_CMD "${RIVE_BUILD_WRAPPER}")
endif()

# Custom build step. BYPRODUCTS is what lets downstream targets take a file
# dependency on the libs (OUTPUT-only wouldn't, because the wrapper premake
# file is regenerated on every configure).
add_custom_command(
    OUTPUT ${RIVE_ALL_LIBS}
    COMMAND ${RIVE_BUILD_CMD}
    WORKING_DIRECTORY "${RIVE_BUILD_DIR}"
    DEPENDS "${RIVE_PREMAKE_WRAPPER}"
    COMMENT "Building rive-runtime (first build ~30-60s, then incremental)"
    VERBATIM
)

add_custom_target(rive_external DEPENDS ${RIVE_ALL_LIBS})

# Public-facing target. INTERFACE because we don't own any compiled sources
# for it — we just stitch together the upstream-built libs + headers.
add_library(rive INTERFACE)
add_dependencies(rive rive_external)
target_link_libraries(rive INTERFACE ${RIVE_ALL_LIBS})

# Rive's public headers. Internal-to-rive includes (harfbuzz/src,
# sheenbidi/Headers) aren't needed by consumers since rive wraps them.
target_include_directories(rive INTERFACE "${RIVE_RUNTIME_DIR}/include")

# Frameworks rive's Apple font backend (src/text/font_hb_apple.mm) needs.
if(APPLE)
    target_link_libraries(rive INTERFACE
        "-framework Foundation"
        "-framework CoreGraphics"
        "-framework CoreText"
    )
endif()
