# BuildRive.cmake
#
# Drives rive-runtime's premake/gmake2/msbuild build from CMake and exposes
# the resulting static libraries + headers as the `rive` INTERFACE target.
#
# Why premake: rive-runtime is built with premake5, not CMake. Rather than
# porting ~hundreds of sources to our CMakeLists, we invoke upstream's own
# build script (build/build_rive.sh on macOS/Linux, build_rive.ps1 on
# Windows). The script self-bootstraps premake5 on first run. Expect the
# first configure to spend 30-60s on that; subsequent configures are fast
# because premake's output is cached.
#
# Build scope:
#   - Core `rive` static lib and its in-tree deps (harfbuzz, sheenbidi,
#     yoga, miniaudio).
#   - Text + layout enabled via premake's default `--with_rive_text
#     --with_rive_layout`.
#   - GPU renderer (`rive_pls_renderer`) is NOT built here — this spike
#     renders via QPainter. That's a follow-up.
#
# Consumer usage:
#   target_link_libraries(<target> PRIVATE rive)

# Resolve paths relative to this module's directory so consumer projects
# adding us via add_subdirectory still find the submodule correctly —
# CMAKE_SOURCE_DIR would point at the host's top-level in that case.
get_filename_component(_rive_qt_plugin_dir "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
set(RIVE_RUNTIME_DIR "${_rive_qt_plugin_dir}/third_party/rive-runtime")
set(RIVE_BUILD_DIR "${CMAKE_BINARY_DIR}/rive-build")

# Release only for now. Debug doubles library sizes and the perf hit of a
# debug rive build isn't worth it during development — the spike target is
# "frame on screen", not "step through rive internals".
set(RIVE_CONFIG "release")
set(RIVE_OUT_DIR "${RIVE_BUILD_DIR}/out/${RIVE_CONFIG}")

# Generated wrapper premake file. build_rive.sh expects a premake5.lua in
# the working directory; upstream's root has premake5_v2.lua instead. The
# wrapper just resolves the submodule path and dofiles into upstream.
set(RIVE_PREMAKE_WRAPPER "${RIVE_BUILD_DIR}/premake5.lua")

file(MAKE_DIRECTORY "${RIVE_BUILD_DIR}")
file(WRITE "${RIVE_PREMAKE_WRAPPER}"
"-- Auto-generated by cmake/BuildRive.cmake — do not edit.\n"
"RIVE_RUNTIME_DIR = '${RIVE_RUNTIME_DIR}'\n"
"dofile(RIVE_RUNTIME_DIR .. '/build/rive_build_config.lua')\n"
"dofile(RIVE_RUNTIME_DIR .. '/premake5_v2.lua')\n")

# Static libs produced by the rive build that we consume.
# Note: libluau_vm.a is a stub (scripting disabled) — not linked.
if(WIN32)
    set(_rive_lib_prefix "")
    set(_rive_lib_suffix ".lib")
else()
    set(_rive_lib_prefix "lib")
    set(_rive_lib_suffix ".a")
endif()

set(RIVE_CORE_LIB   "${RIVE_OUT_DIR}/${_rive_lib_prefix}rive${_rive_lib_suffix}")
set(RIVE_HARFBUZZ   "${RIVE_OUT_DIR}/${_rive_lib_prefix}rive_harfbuzz${_rive_lib_suffix}")
set(RIVE_SHEENBIDI  "${RIVE_OUT_DIR}/${_rive_lib_prefix}rive_sheenbidi${_rive_lib_suffix}")
set(RIVE_YOGA       "${RIVE_OUT_DIR}/${_rive_lib_prefix}rive_yoga${_rive_lib_suffix}")
set(RIVE_MINIAUDIO  "${RIVE_OUT_DIR}/${_rive_lib_prefix}miniaudio${_rive_lib_suffix}")

set(RIVE_ALL_LIBS
    "${RIVE_CORE_LIB}"
    "${RIVE_HARFBUZZ}"
    "${RIVE_SHEENBIDI}"
    "${RIVE_YOGA}"
    "${RIVE_MINIAUDIO}"
)

# Wrapper script. Two reasons we need one:
#
# 1. Ninja pre-creates the parent directory of any custom-command OUTPUT, so
#    by the time build_rive.{sh,ps1} runs, "out/release/" already exists.
#    Upstream's script treats a pre-existing OUT dir as an incremental build
#    and fails when its marker file `.rive_premake_args` is missing.
#    Solution: drop the dir if the marker is absent, then delegate.
#
# 2. On macOS we scrub the PATH of Anaconda/homebrew toolchain shims —
#    observed `warning: /opt/homebrew/anaconda3/bin/arm64-apple-darwin20.0.0-ranlib`
#    corrupting librive.a's symbol table. Xcode's clang/ar/ranlib will be
#    found via /usr/bin / CommandLineTools.
#
# On Windows we generate a .ps1 script on disk and invoke with -File. Passing
# multi-statement logic via -Command through CMake's list expansion is a
# quoting nightmare (observed: `&` at arg boundary interpreted as the
# pipeline operator and rejected).
if(WIN32)
    set(RIVE_BUILD_WRAPPER "${RIVE_BUILD_DIR}/build_rive_wrapper.ps1")
    # Pin premake to beta8 on Windows. beta7 (rive's default) has a Lua
    # nil-format bug in vs2010_vcxproj.lua that crashes while generating
    # Premake5.vcxproj with current VS 2022 17.14, killing the bootstrap
    # before MSBuild can produce the real premake5.exe. beta8's VS
    # generator is patched. Mac/Linux stay on rive's beta7 default —
    # they've been exercised and work.
    set(RIVE_PREMAKE_TAG "v5.0.0-beta8")
    file(TO_NATIVE_PATH "${RIVE_BUILD_DIR}" _rive_build_dir_native)
    file(TO_NATIVE_PATH "${RIVE_RUNTIME_DIR}/build/build_rive.sh" _rive_build_sh_native)
    file(TO_NATIVE_PATH "${RIVE_RUNTIME_DIR}/build/setup_windows_dev.ps1" _rive_setup_ps1_native)
    file(TO_NATIVE_PATH "${RIVE_RUNTIME_DIR}/build/dependencies/premake-core" _rive_premake_core_native)
    file(TO_NATIVE_PATH "${RIVE_RUNTIME_DIR}/build/dependencies/premake-core/bin/${RIVE_PREMAKE_TAG}_release" _rive_premake_install_native)
    # NOTE: we don't invoke upstream's build_rive.ps1 because it does
    # `sh build_rive.sh` (no path), which relies on CWD == rive's build
    # directory. Our wrapper CWD is the CMake build dir (for the
    # generated premake5.lua), so we call `sh` with the full path to
    # build_rive.sh ourselves. We keep the setup_windows_dev.ps1 step
    # so msbuild/fxc are on PATH when invoked from a bare shell.
    file(WRITE "${RIVE_BUILD_WRAPPER}"
"# Auto-generated by cmake/BuildRive.cmake — do not edit.\n"
"$ErrorActionPreference = 'Stop'\n"
"Set-Location -LiteralPath '${_rive_build_dir_native}'\n"
"$out = 'out/${RIVE_CONFIG}'\n"
"if ((Test-Path $out) -and -not (Test-Path \"$out/.rive_premake_args\")) {\n"
"    Remove-Item -Recurse -Force $out\n"
"}\n"
"\n"
"# Ensure sh.exe is discoverable.\n"
"if (-not (Get-Command sh -ErrorAction SilentlyContinue)) {\n"
"    $candidates = @(\n"
"        \"$Env:ProgramFiles\\Git\\usr\\bin\",\n"
"        \"$Env:ProgramFiles\\Git\\bin\",\n"
"        \"\${Env:ProgramFiles(x86)}\\Git\\usr\\bin\",\n"
"        \"$Env:LOCALAPPDATA\\Programs\\Git\\usr\\bin\"\n"
"    )\n"
"    # Derive from git.exe as a fallback — sh lives in <git>\\..\\usr\\bin\\.\n"
"    $git = (Get-Command git -ErrorAction SilentlyContinue).Source\n"
"    if ($git) {\n"
"        $candidates += (Join-Path (Split-Path (Split-Path $git)) 'usr\\bin')\n"
"    }\n"
"    foreach ($d in $candidates) {\n"
"        if ($d -and (Test-Path (Join-Path $d 'sh.exe'))) {\n"
"            $Env:Path = \"$d;$Env:Path\"\n"
"            break\n"
"        }\n"
"    }\n"
"    if (-not (Get-Command sh -ErrorAction SilentlyContinue)) {\n"
"        Write-Error 'No sh.exe found. Install Git for Windows (ships sh at <git>\\usr\\bin\\sh.exe) or put a bash on PATH.'\n"
"        exit 1\n"
"    }\n"
"}\n"
"\n"
"# Ensure fxc/msbuild are on PATH by running rive's VsDevShell setup\n"
"# if they aren't already available (Qt Creator's MSVC kit usually\n"
"# provides them, but bare shells won't).\n"
"if (-not (Get-Command fxc -ErrorAction SilentlyContinue)) {\n"
"    & '${_rive_setup_ps1_native}'\n"
"}\n"
"\n"
"# Wipe a stale Mach-O/ELF premake5 left over from a shared-FS Mac or\n"
"# Linux build. Rive's bootstrap keys on `test -f premake5`, not on\n"
"# the exe suffix, so a bare `premake5` file from a foreign OS would\n"
"# be kept and then fail to execute here with \"Exec format error\".\n"
"# On Windows the bootstrap produces premake5.exe, so if we see a\n"
"# bare `premake5` but no `premake5.exe`, it's not ours.\n"
"$riveInstallDir = '${_rive_premake_install_native}'\n"
"if ((Test-Path (Join-Path $riveInstallDir 'premake5')) -and -not (Test-Path (Join-Path $riveInstallDir 'premake5.exe'))) {\n"
"    Remove-Item -Recurse -Force '${_rive_premake_core_native}'\n"
"}\n"
"\n"
"# Scrub PLATFORM from the environment. Qt Creator's ARM64 MSVC kit\n"
"# sets PLATFORM=arm64, which premake-core's Bootstrap.bat/.mak\n"
"# forwards as --arch=arm64 to the bootstrap binary. Premake beta7\n"
"# only knows x86 / x86_64 / arm — it rejects arm64 with\n"
"# \"Error: invalid value 'arm64' for option 'arch'\". The bootstrap\n"
"# binary runs on the host via Windows-on-ARM x86 emulation anyway.\n"
"Remove-Item Env:PLATFORM -ErrorAction SilentlyContinue\n"
"\n"
"# Pin the premake tag rive will clone / bootstrap. See BuildRive.cmake.\n"
"$Env:RIVE_PREMAKE_TAG = '${RIVE_PREMAKE_TAG}'\n"
"\n"
"# ==============================================================\n"
"# Pre-bootstrap premake ourselves with a patch to vs2010_vcxproj.lua.\n"
"# ==============================================================\n"
"# Upstream premake (beta7 and beta8 both) has a latent bug in its VS\n"
"# XML generator: m.element() calls string.format once to wrap the\n"
"# element name+value+name, then passes the RESULT through premake.w,\n"
"# which calls string.format a SECOND time. If the value contains\n"
"# legit-looking %X sequences (rive's cfg.defines end up with %%(...)\n"
"# for MSBuild's parent-inheritance syntax, which collapses to %(...)\n"
"# after the first format) the second format call fails:\n"
"#   bad argument #2 to 'format' (no value)\n"
"# Kills Premake5.vcxproj generation, which kills the whole bootstrap.\n"
"#\n"
"# Fix: when m.element has no format args, skip the second format pass\n"
"# by writing the built string directly via p.outln. Apply the patch,\n"
"# run Bootstrap.bat ourselves, install into rive's expected path.\n"
"# Rive's script then sees premake5 installed and skips its bootstrap.\n"
"if (-not (Test-Path (Join-Path '${_rive_premake_install_native}' 'premake5.exe'))) {\n"
"    Write-Host '=== Bootstrapping premake-core (${RIVE_PREMAKE_TAG}) with patched vs2010_vcxproj.lua ==='\n"
"    $premakeCore = '${_rive_premake_core_native}'\n"
"\n"
"    # Clone fresh (wipe any stale checkout).\n"
"    if (Test-Path $premakeCore) { Remove-Item -Recurse -Force $premakeCore }\n"
"    & git clone --depth 1 --branch ${RIVE_PREMAKE_TAG} https://github.com/premake/premake-core.git $premakeCore\n"
"    if ($LASTEXITCODE -ne 0) { Write-Error 'premake-core clone failed'; exit 1 }\n"
"\n"
"    # Patch vs2010_vcxproj.lua. The bug: m.element builds an XML element\n"
"    # string via string.format, then calls p.w (which calls string.format\n"
"    # AGAIN). Any literal % in the built string — e.g. the `;%%(Preprocessor\n"
"    # Definitions)` MSBuild-inheritance marker that collapses to `%(…)`\n"
"    # after the first format pass — trips the second pass.\n"
"    # Fix: pre-escape % to %% in the built string so the second\n"
"    # string.format treats it as literal. Single-quoted PS strings so\n"
"    # backslashes/percents aren't PS-interpreted.\n"
"    $vcxprojLua = Join-Path $premakeCore 'modules\\vstudio\\vs2010_vcxproj.lua'\n"
"    $content = [System.IO.File]::ReadAllText($vcxprojLua)\n"
"    $old = 'p.w(format, table.unpack(arg))'\n"
"    $new = 'if #arg == 0 then p.w((format:gsub(\"%%\", \"%%%%\"))) else p.w(format, table.unpack(arg)) end'\n"
"    if ($content.Contains($old)) {\n"
"        # Replace the FIRST occurrence only — there may be similar lines\n"
"        # elsewhere we don't want to touch.\n"
"        $idx = $content.IndexOf($old)\n"
"        $patched = $content.Substring(0, $idx) + $new + $content.Substring($idx + $old.Length)\n"
"        [System.IO.File]::WriteAllText($vcxprojLua, $patched)\n"
"        Write-Host 'Patched vs2010_vcxproj.lua'\n"
"    } else {\n"
"        Write-Error 'Could not locate p.w(format, table.unpack(arg)) in vs2010_vcxproj.lua. Upstream may have changed.'\n"
"        exit 1\n"
"    }\n"
"\n"
"    # Run upstream Bootstrap.bat ourselves (same sequence rive would).\n"
"    Push-Location $premakeCore\n"
"    try {\n"
"        & cmd /c 'Bootstrap.bat vs2022'\n"
"        if ($LASTEXITCODE -ne 0) { Write-Error 'Bootstrap.bat failed'; exit 1 }\n"
"    } finally { Pop-Location }\n"
"\n"
"    # Install to rive's expected path. Both file names so rive's\n"
"    # `[ -f premake5 ]` check passes on subsequent runs.\n"
"    New-Item -ItemType Directory -Force -Path '${_rive_premake_install_native}' | Out-Null\n"
"    $binRelease = Join-Path $premakeCore 'bin\\release'\n"
"    Copy-Item -Force (Join-Path $binRelease 'premake5.exe') (Join-Path '${_rive_premake_install_native}' 'premake5.exe')\n"
"    Copy-Item -Force (Join-Path $binRelease 'premake5.exe') (Join-Path '${_rive_premake_install_native}' 'premake5')\n"
"    Write-Host '=== Premake pre-bootstrapped successfully ==='\n"
"}\n"
"\n"
"# Call build_rive.sh with an explicit path — CWD must stay our CMake\n"
"# build dir so premake finds the generated premake5.lua wrapper.\n"
"# 2>&1 so ninja shows stderr (rive's script pipes stdout through grep,\n"
"# which can swallow premake5 errors depending on buffering).\n"
"& sh '${_rive_build_sh_native}' '${RIVE_CONFIG}' 2>&1\n"
"$riveExit = $LASTEXITCODE\n"
"\n"
"# If the MSBuild'd premake5.exe landed successfully, make sure a bare\n"
"# `premake5` also exists. rive's bootstrap-needed test is\n"
"# `[ ! -f premake5 ]` (no .exe), so without this companion file\n"
"# every subsequent build would pointlessly re-bootstrap premake.\n"
"$installedExe = Join-Path '${_rive_premake_install_native}' 'premake5.exe'\n"
"$installedBare = Join-Path '${_rive_premake_install_native}' 'premake5'\n"
"if ((Test-Path $installedExe) -and -not (Test-Path $installedBare)) {\n"
"    Copy-Item -Force $installedExe $installedBare\n"
"}\n"
"\n"
"# Diagnostic: if rive's script failed silently after the premake echo,\n"
"# re-run premake5 directly so we can see what went wrong.\n"
"if ($riveExit -ne 0 -and (Test-Path $installedExe)) {\n"
"    Write-Host '=== rive script failed — running premake5 standalone for diagnostics ==='\n"
"    & $installedExe 'vs2022' '--config=${RIVE_CONFIG}' '--out=out/${RIVE_CONFIG}' '--with_rive_text' '--with_rive_layout' 2>&1\n"
"    Write-Host \"=== premake5 standalone exit: $LASTEXITCODE ===\"\n"
"}\n"
"\n"
"# (Redundant fallback — pre-bootstrap above should always produce\n"
"# a working premake5.exe. Kept only as a last-ditch in case upstream\n"
"# adds a new incompatibility we haven't patched yet.)\n"
"$installDir = '${_rive_premake_install_native}'\n"
"$bootstrapExe = Join-Path '${_rive_premake_core_native}' 'build\\bootstrap\\premake_bootstrap.exe'\n"
"if ($riveExit -ne 0 -and (Test-Path $bootstrapExe) -and -not (Test-Path (Join-Path $installDir 'premake5.exe'))) {\n"
"    Write-Host 'Falling back to premake_bootstrap as premake5.'\n"
"    New-Item -ItemType Directory -Force -Path $installDir | Out-Null\n"
"    Copy-Item -Force $bootstrapExe (Join-Path $installDir 'premake5.exe')\n"
"    Copy-Item -Force $bootstrapExe (Join-Path $installDir 'premake5')\n"
"    # Clear stale out/release so rive re-runs premake against the\n"
"    # generated wrapper premake5.lua with the now-present exe.\n"
"    if (Test-Path 'out/${RIVE_CONFIG}') { Remove-Item -Recurse -Force 'out/${RIVE_CONFIG}' }\n"
"    & sh '${_rive_build_sh_native}' '${RIVE_CONFIG}'\n"
"    $riveExit = $LASTEXITCODE\n"
"}\n"
"exit $riveExit\n")
else()
    set(RIVE_BUILD_WRAPPER "${RIVE_BUILD_DIR}/build_rive_wrapper.sh")
    file(WRITE "${RIVE_BUILD_WRAPPER}"
"#!/bin/bash\n"
"# Auto-generated by cmake/BuildRive.cmake — do not edit.\n"
"set -e\n"
"cd \"${RIVE_BUILD_DIR}\"\n"
"RIVE_OUT=\"out/${RIVE_CONFIG}\"\n"
"if [ -d \"$RIVE_OUT\" ] && [ ! -f \"$RIVE_OUT/.rive_premake_args\" ]; then\n"
"    rm -rf \"$RIVE_OUT\"\n"
"fi\n"
"# Wipe a stale Windows-built premake5.exe left from a shared-FS\n"
"# Windows build — it'd fool rive's bootstrap test into using a PE\n"
"# binary on a Unix host.\n"
"RIVE_PREMAKE_INSTALL=\"${RIVE_RUNTIME_DIR}/build/dependencies/premake-core/bin/v5.0.0-beta7_release\"\n"
"if [ -f \"$RIVE_PREMAKE_INSTALL/premake5.exe\" ] && [ ! -x \"$RIVE_PREMAKE_INSTALL/premake5\" ]; then\n"
"    rm -rf \"${RIVE_RUNTIME_DIR}/build/dependencies/premake-core\"\n"
"fi\n"
"exec \"${RIVE_RUNTIME_DIR}/build/build_rive.sh\" \"${RIVE_CONFIG}\"\n")
    execute_process(COMMAND chmod +x "${RIVE_BUILD_WRAPPER}")
endif()

if(APPLE)
    set(RIVE_BUILD_CMD
        "${CMAKE_COMMAND}" -E env
        "PATH=/usr/bin:/bin:/usr/sbin:/sbin:/Library/Developer/CommandLineTools/usr/bin"
        "${RIVE_BUILD_WRAPPER}"
    )
elseif(WIN32)
    set(RIVE_BUILD_CMD
        powershell -ExecutionPolicy Bypass -NoProfile -File "${RIVE_BUILD_WRAPPER}"
    )
else()
    set(RIVE_BUILD_CMD "${RIVE_BUILD_WRAPPER}")
endif()

# Custom build step. BYPRODUCTS is what lets downstream targets take a file
# dependency on the libs (OUTPUT-only wouldn't, because the wrapper premake
# file is regenerated on every configure).
add_custom_command(
    OUTPUT ${RIVE_ALL_LIBS}
    COMMAND ${RIVE_BUILD_CMD}
    WORKING_DIRECTORY "${RIVE_BUILD_DIR}"
    DEPENDS "${RIVE_PREMAKE_WRAPPER}"
    COMMENT "Building rive-runtime (first build ~30-60s, then incremental)"
    VERBATIM
)

add_custom_target(rive_external DEPENDS ${RIVE_ALL_LIBS})

# Public-facing target. INTERFACE because we don't own any compiled sources
# for it — we just stitch together the upstream-built libs + headers.
add_library(rive INTERFACE)
add_dependencies(rive rive_external)
target_link_libraries(rive INTERFACE ${RIVE_ALL_LIBS})

# Rive's public headers. Internal-to-rive includes (harfbuzz/src,
# sheenbidi/Headers) aren't needed by consumers since rive wraps them.
target_include_directories(rive INTERFACE "${RIVE_RUNTIME_DIR}/include")

# Frameworks rive's Apple font backend (src/text/font_hb_apple.mm) needs.
if(APPLE)
    target_link_libraries(rive INTERFACE
        "-framework Foundation"
        "-framework CoreGraphics"
        "-framework CoreText"
    )
endif()
