# BuildRive.cmake
#
# Drives rive-runtime's premake/gmake2/msbuild build from CMake and exposes
# the resulting static libraries + headers as the `rive` INTERFACE target.
#
# Why premake: rive-runtime is built with premake5, not CMake. Rather than
# porting ~hundreds of sources to our CMakeLists, we invoke upstream's own
# build script (build/build_rive.sh on macOS/Linux, build_rive.ps1 on
# Windows). The script self-bootstraps premake5 on first run. Expect the
# first configure to spend 30-60s on that; subsequent configures are fast
# because premake's output is cached.
#
# Build scope:
#   - Core `rive` static lib and its in-tree deps (harfbuzz, sheenbidi,
#     yoga, miniaudio).
#   - Text + layout enabled via premake's default `--with_rive_text
#     --with_rive_layout`.
#   - GPU renderer (`rive_pls_renderer`) is NOT built here — this spike
#     renders via QPainter. That's a follow-up.
#
# Consumer usage:
#   target_link_libraries(<target> PRIVATE rive)

# Resolve paths relative to this module's directory so consumer projects
# adding us via add_subdirectory still find the submodule correctly —
# CMAKE_SOURCE_DIR would point at the host's top-level in that case.
get_filename_component(_rive_qt_plugin_dir "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
set(RIVE_RUNTIME_DIR "${_rive_qt_plugin_dir}/third_party/rive-runtime")
set(RIVE_BUILD_DIR "${CMAKE_BINARY_DIR}/rive-build")

# Release only for now. Debug doubles library sizes and the perf hit of a
# debug rive build isn't worth it during development — the spike target is
# "frame on screen", not "step through rive internals".
set(RIVE_CONFIG "release")
set(RIVE_OUT_DIR "${RIVE_BUILD_DIR}/out/${RIVE_CONFIG}")

# Generated wrapper premake file. build_rive.sh expects a premake5.lua in
# the working directory; upstream's root has premake5_v2.lua instead. The
# wrapper just resolves the submodule path and dofiles into upstream.
set(RIVE_PREMAKE_WRAPPER "${RIVE_BUILD_DIR}/premake5.lua")

file(MAKE_DIRECTORY "${RIVE_BUILD_DIR}")
file(WRITE "${RIVE_PREMAKE_WRAPPER}"
"-- Auto-generated by cmake/BuildRive.cmake — do not edit.\n"
"RIVE_RUNTIME_DIR = '${RIVE_RUNTIME_DIR}'\n"
"dofile(RIVE_RUNTIME_DIR .. '/build/rive_build_config.lua')\n"
"dofile(RIVE_RUNTIME_DIR .. '/premake5_v2.lua')\n")

# Static libs produced by the rive build that we consume.
# Note: libluau_vm.a is a stub (scripting disabled) — not linked.
if(WIN32)
    set(_rive_lib_prefix "")
    set(_rive_lib_suffix ".lib")
else()
    set(_rive_lib_prefix "lib")
    set(_rive_lib_suffix ".a")
endif()

set(RIVE_CORE_LIB   "${RIVE_OUT_DIR}/${_rive_lib_prefix}rive${_rive_lib_suffix}")
set(RIVE_HARFBUZZ   "${RIVE_OUT_DIR}/${_rive_lib_prefix}rive_harfbuzz${_rive_lib_suffix}")
set(RIVE_SHEENBIDI  "${RIVE_OUT_DIR}/${_rive_lib_prefix}rive_sheenbidi${_rive_lib_suffix}")
set(RIVE_YOGA       "${RIVE_OUT_DIR}/${_rive_lib_prefix}rive_yoga${_rive_lib_suffix}")
set(RIVE_MINIAUDIO  "${RIVE_OUT_DIR}/${_rive_lib_prefix}miniaudio${_rive_lib_suffix}")

set(RIVE_ALL_LIBS
    "${RIVE_CORE_LIB}"
    "${RIVE_HARFBUZZ}"
    "${RIVE_SHEENBIDI}"
    "${RIVE_YOGA}"
    "${RIVE_MINIAUDIO}"
)

# Wrapper script. Two reasons we need one:
#
# 1. Ninja pre-creates the parent directory of any custom-command OUTPUT, so
#    by the time build_rive.{sh,ps1} runs, "out/release/" already exists.
#    Upstream's script treats a pre-existing OUT dir as an incremental build
#    and fails when its marker file `.rive_premake_args` is missing.
#    Solution: drop the dir if the marker is absent, then delegate.
#
# 2. On macOS we scrub the PATH of Anaconda/homebrew toolchain shims —
#    observed `warning: /opt/homebrew/anaconda3/bin/arm64-apple-darwin20.0.0-ranlib`
#    corrupting librive.a's symbol table. Xcode's clang/ar/ranlib will be
#    found via /usr/bin / CommandLineTools.
#
# On Windows we generate a .ps1 script on disk and invoke with -File. Passing
# multi-statement logic via -Command through CMake's list expansion is a
# quoting nightmare (observed: `&` at arg boundary interpreted as the
# pipeline operator and rejected).
if(WIN32)
    set(RIVE_BUILD_WRAPPER "${RIVE_BUILD_DIR}/build_rive_wrapper.ps1")
    set(RIVE_PREMAKE_TAG "v5.0.0-beta8")
    set(RIVE_PREMAKE_INSTALL_DIR "${RIVE_RUNTIME_DIR}/build/dependencies/premake-core/bin/${RIVE_PREMAKE_TAG}_release")
    set(RIVE_PREMAKE_VENDORED "${CMAKE_CURRENT_LIST_DIR}/vendor/premake5-windows-x64.exe")
    set(RIVE_PREMAKE_CORE_DIR "${RIVE_RUNTIME_DIR}/build/dependencies/premake-core")

    # Detect whether we're building on Windows ARM64. The vendored
    # prebuilt premake5.exe is x86-64, which segfaults under Prism
    # (Windows-on-ARM x64 emulation) when processing rive's premake
    # files. On ARM64 we bootstrap premake natively from source using
    # the ARM64 MSVC tools; on x64 the vendored binary runs natively.
    # Belt-and-suspenders: check both the target and host processor —
    # some toolchain setups populate only one of them.
    if(CMAKE_SYSTEM_PROCESSOR MATCHES "^(ARM64|arm64|aarch64|AARCH64)$"
            OR CMAKE_HOST_SYSTEM_PROCESSOR MATCHES "^(ARM64|arm64|aarch64|AARCH64)$")
        set(_rive_windows_arm64 TRUE)
    else()
        set(_rive_windows_arm64 FALSE)
    endif()
    message(STATUS
        "BuildRive: Windows, CMAKE_SYSTEM_PROCESSOR=${CMAKE_SYSTEM_PROCESSOR}, "
        "CMAKE_HOST_SYSTEM_PROCESSOR=${CMAKE_HOST_SYSTEM_PROCESSOR}, "
        "arm64=${_rive_windows_arm64}")

    file(TO_NATIVE_PATH "${RIVE_BUILD_DIR}" _rive_build_dir_native)
    file(TO_NATIVE_PATH "${RIVE_RUNTIME_DIR}/build/build_rive.sh" _rive_build_sh_native)
    file(TO_NATIVE_PATH "${RIVE_RUNTIME_DIR}/build/setup_windows_dev.ps1" _rive_setup_ps1_native)
    file(TO_NATIVE_PATH "${RIVE_PREMAKE_INSTALL_DIR}" _rive_premake_install_native)
    file(TO_NATIVE_PATH "${RIVE_PREMAKE_VENDORED}" _rive_premake_vendored_native)
    file(TO_NATIVE_PATH "${RIVE_PREMAKE_CORE_DIR}" _rive_premake_core_native)

    file(WRITE "${RIVE_BUILD_WRAPPER}"
"# Auto-generated by cmake/BuildRive.cmake — do not edit.\n"
"$ErrorActionPreference = 'Stop'\n"
"Set-Location -LiteralPath '${_rive_build_dir_native}'\n"
"$out = 'out/${RIVE_CONFIG}'\n"
"if ((Test-Path $out) -and -not (Test-Path \"$out/.rive_premake_args\")) {\n"
"    Remove-Item -Recurse -Force $out\n"
"}\n"
"\n"
"# Rive's build_rive.sh shells out to sh. Qt Creator's build env doesn't\n"
"# inherit Git-for-Windows' usr\\bin where sh.exe lives, so find it and\n"
"# prepend to PATH.\n"
"if (-not (Get-Command sh -ErrorAction SilentlyContinue)) {\n"
"    $candidates = @(\n"
"        \"$Env:ProgramFiles\\Git\\usr\\bin\",\n"
"        \"$Env:ProgramFiles\\Git\\bin\",\n"
"        \"\${Env:ProgramFiles(x86)}\\Git\\usr\\bin\",\n"
"        \"$Env:LOCALAPPDATA\\Programs\\Git\\usr\\bin\"\n"
"    )\n"
"    $git = (Get-Command git -ErrorAction SilentlyContinue).Source\n"
"    if ($git) {\n"
"        $candidates += (Join-Path (Split-Path (Split-Path $git)) 'usr\\bin')\n"
"    }\n"
"    foreach ($d in $candidates) {\n"
"        if ($d -and (Test-Path (Join-Path $d 'sh.exe'))) {\n"
"            $Env:Path = \"$d;$Env:Path\"\n"
"            break\n"
"        }\n"
"    }\n"
"    if (-not (Get-Command sh -ErrorAction SilentlyContinue)) {\n"
"        Write-Error 'No sh.exe found. Install Git for Windows.'\n"
"        exit 1\n"
"    }\n"
"}\n"
"\n"
"# Pin the tag rive uses for its PREMAKE_INSTALL_DIR path calculation.\n"
"$Env:RIVE_PREMAKE_TAG = '${RIVE_PREMAKE_TAG}'\n"
"\n"
"$installDir = '${_rive_premake_install_native}'\n"
)
    if(_rive_windows_arm64)
        file(APPEND "${RIVE_BUILD_WRAPPER}"
"# Windows ARM64 path: build premake natively for ARM64.\n"
"# The vendored x86-64 premake5.exe segfaults under Prism emulation\n"
"# when processing rive's premake files. Native ARM64 cl/msbuild\n"
"# produces an ARM64 premake that runs without emulation.\n"
"#\n"
"# Verify the installed binary's real PE machine type, not just a text\n"
"# marker. Earlier iterations wrote 'arm64' to the marker after an\n"
"# install that turned out to be x64 (Bootstrap.bat had overridden\n"
"# our env), leaving a stale x64 binary the guard happily accepted.\n"
"# Read the actual IMAGE_FILE_HEADER.Machine field.\n"
"function Get-PeMachine($path) {\n"
"    try {\n"
"        $fs = [System.IO.File]::OpenRead($path)\n"
"        try {\n"
"            $buf = New-Object byte[] 4096\n"
"            [void]$fs.Read($buf, 0, 4096)\n"
"            $peOffset = [BitConverter]::ToInt32($buf, 0x3C)\n"
"            $machine = [BitConverter]::ToUInt16($buf, $peOffset + 4)\n"
"            switch ($machine) {\n"
"                0x014c { 'x86' }\n"
"                0x8664 { 'x64' }\n"
"                0xAA64 { 'arm64' }\n"
"                default { 'other' }\n"
"            }\n"
"        } finally { $fs.Close() }\n"
"    } catch { 'error' }\n"
"}\n"
"$installedExe = Join-Path $installDir 'premake5.exe'\n"
"$installedArch = if (Test-Path $installedExe) { Get-PeMachine $installedExe } else { '' }\n"
"if ($installedArch -ne 'arm64' -and (Test-Path $installDir)) {\n"
"    Write-Host \"Wiping stale premake install (detected arch='$installedArch', need arm64)\"\n"
"    Remove-Item -Recurse -Force $installDir\n"
"}\n"
"if (-not (Test-Path (Join-Path $installDir 'premake5.exe'))) {\n"
"    Write-Host '=== Building native ARM64 premake5.exe ==='\n"
"    $premakeCore = '${_rive_premake_core_native}'\n"
"\n"
"    # Locate vcvarsall.bat. Launch-VsDevShell.ps1 would be tidier but\n"
"    # older VS 2022 installs ship it with -HostArch restricted to\n"
"    # x86/amd64 (no arm64 in the ValidateSet). vcvarsall.bat accepts\n"
"    # 'arm64' (native ARM64 host+target) and 'amd64_arm64'\n"
"    # (cross-compile from x64 host to ARM64 target) across all recent\n"
"    # VS 2022 versions, so we go directly to it.\n"
"    $vcvarsCandidates = @(\n"
"        \"$Env:ProgramFiles\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Auxiliary\\Build\\vcvarsall.bat\",\n"
"        \"$Env:ProgramFiles\\Microsoft Visual Studio\\2022\\Professional\\VC\\Auxiliary\\Build\\vcvarsall.bat\",\n"
"        \"$Env:ProgramFiles\\Microsoft Visual Studio\\2022\\Community\\VC\\Auxiliary\\Build\\vcvarsall.bat\",\n"
"        \"$Env:ProgramFiles\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Auxiliary\\Build\\vcvarsall.bat\"\n"
"    )\n"
"    $vcvarsall = $null\n"
"    foreach ($p in $vcvarsCandidates) {\n"
"        if (Test-Path $p) { $vcvarsall = $p; break }\n"
"    }\n"
"    if (-not $vcvarsall) {\n"
"        Write-Error 'vcvarsall.bat not found. Install VS 2022 with MSVC ARM64 build tools.'\n"
"        exit 1\n"
"    }\n"
"\n"
"    # Import vcvarsall's env into this PowerShell session. Try native\n"
"    # ARM64 host first; if the ARM64 host tools aren't installed (only\n"
"    # cross tools are), fall back to amd64_arm64 (x64-hosted ARM64\n"
"    # cross-compiler) — the produced premake5.exe would then be x64.\n"
"    # We prefer native ARM64 because the whole point is to avoid Prism.\n"
"    function Import-VcEnv($vcvars, $arch) {\n"
"        $out = cmd /c \"`\"$vcvars`\" $arch >NUL 2>NUL && set\"\n"
"        if ($LASTEXITCODE -ne 0) { return $false }\n"
"        foreach ($line in $out) {\n"
"            if ($line -match '^([^=]+)=(.*)$') {\n"
"                Set-Item -Path \"Env:$($Matches[1])\" -Value $Matches[2] -ErrorAction SilentlyContinue\n"
"            }\n"
"        }\n"
"        return $true\n"
"    }\n"
"    $vcArchTried = 'arm64'\n"
"    if (-not (Import-VcEnv $vcvarsall 'arm64')) {\n"
"        Write-Host 'vcvarsall.bat arm64 failed; trying amd64_arm64 cross-compile.'\n"
"        $vcArchTried = 'amd64_arm64'\n"
"        if (-not (Import-VcEnv $vcvarsall 'amd64_arm64')) {\n"
"            Write-Error 'Neither arm64 nor amd64_arm64 env init succeeded. ARM64 MSVC tools likely not installed.'\n"
"            exit 1\n"
"        }\n"
"    }\n"
"    Write-Host \"vcvarsall.bat initialized with arch=$vcArchTried\"\n"
"    if (-not (Get-Command cl -ErrorAction SilentlyContinue)) {\n"
"        Write-Error 'cl.exe still not on PATH after vcvarsall init.'\n"
"        exit 1\n"
"    }\n"
"\n"
"    # Fresh clone.\n"
"    if (Test-Path $premakeCore) { Remove-Item -Recurse -Force $premakeCore }\n"
"    & git clone --depth 1 --branch ${RIVE_PREMAKE_TAG} https://github.com/premake/premake-core.git $premakeCore\n"
"    if ($LASTEXITCODE -ne 0) { Write-Error 'premake-core clone failed'; exit 1 }\n"
"\n"
"    # Patch vs2010_vcxproj.lua for the %%-format bug that kills the\n"
"    # Premake5.vcxproj generation step. See commit history for why.\n"
"    $vcxprojLua = Join-Path $premakeCore 'modules\\vstudio\\vs2010_vcxproj.lua'\n"
"    $content = [System.IO.File]::ReadAllText($vcxprojLua)\n"
"    $old = 'p.w(format, table.unpack(arg))'\n"
"    $new = 'if #arg == 0 then p.w((format:gsub(\"%%%%\", \"%%\"):gsub(\"%%\", \"%%%%\"))) else p.w(format, table.unpack(arg)) end'\n"
"    if ($content.Contains($old)) {\n"
"        $idx = $content.IndexOf($old)\n"
"        [System.IO.File]::WriteAllText($vcxprojLua, $content.Substring(0, $idx) + $new + $content.Substring($idx + $old.Length))\n"
"        Write-Host 'Patched vs2010_vcxproj.lua'\n"
"    }\n"
"\n"
"    # Skip Bootstrap.bat entirely — it CALLs vcvars64.bat internally\n"
"    # which resets our ARM64 env back to x64 (observed: mid-build\n"
"    # [vcvarsall.bat] Environment initialized for: 'x64'). Call nmake\n"
"    # directly against Bootstrap.mak instead. nmake is on PATH\n"
"    # because we already ran vcvarsall arm64.\n"
"    #\n"
"    # PLATFORM=aarch64 because premake beta8's arch allowed list is\n"
"    # 'universal,x86,x86_64,arm,aarch64,…' — lowercase arm64 is NOT\n"
"    # in it; only aarch64 (canonical) or ARM64 (uppercase alias) work.\n"
"    # See src/_premake_init.lua in premake-core.\n"
"    $Env:PLATFORM = 'aarch64'\n"
"    Push-Location $premakeCore\n"
"    try {\n"
"        & nmake /NOLOGO -f Bootstrap.mak windows MSDEV=vs2022 PLATFORM=aarch64\n"
"        $bootstrapExit = $LASTEXITCODE\n"
"    } finally { Pop-Location }\n"
"\n"
"    # Prefer the MSBuild'd release binary; if the Premake5 project's\n"
"    # scripts.c compile bug hits again, fall back to the bootstrap exe\n"
"    # (which by this point is ARM64 native with patched Lua embedded).\n"
"    $binRelease = Join-Path $premakeCore 'bin\\release'\n"
"    $releaseExe = Join-Path $binRelease 'premake5.exe'\n"
"    $bootstrapExe = Join-Path $premakeCore 'build\\bootstrap\\premake_bootstrap.exe'\n"
"    if (Test-Path $releaseExe) {\n"
"        $sourceExe = $releaseExe\n"
"    } elseif (Test-Path $bootstrapExe) {\n"
"        $sourceExe = $bootstrapExe\n"
"        Write-Host 'Using ARM64 premake_bootstrap.exe (Premake5 MSBuild step failed).'\n"
"    } else {\n"
"        Write-Error \"No premake binary produced (Bootstrap.bat exit $bootstrapExit).\"\n"
"        exit 1\n"
"    }\n"
"\n"
"    New-Item -ItemType Directory -Force -Path $installDir | Out-Null\n"
"    Copy-Item -Force $sourceExe (Join-Path $installDir 'premake5.exe')\n"
"    Copy-Item -Force $sourceExe (Join-Path $installDir 'premake5')\n"
"\n"
"    # Sanity-check: the binary we just installed MUST be ARM64.\n"
"    # If Bootstrap.mak / nmake reverted to x64 somehow, catch it here\n"
"    # rather than shipping a broken install that next build will trust.\n"
"    $finalArch = Get-PeMachine (Join-Path $installDir 'premake5.exe')\n"
"    if ($finalArch -ne 'arm64') {\n"
"        Write-Error \"Installed premake5.exe is $finalArch, not arm64. The bootstrap didn't use the ARM64 toolchain. Check vcvarsall init.\"\n"
"        Remove-Item -Recurse -Force $installDir\n"
"        exit 1\n"
"    }\n"
"    Write-Host '=== Native ARM64 premake installed ==='\n"
"}\n"
)
    else()
        file(APPEND "${RIVE_BUILD_WRAPPER}"
"# Windows x64 path: vendored x86-64 premake5.exe runs natively.\n"
"# PE header check so a stale ARM64 install (from a kit switch) gets\n"
"# wiped automatically.\n"
"function Get-PeMachine($path) {\n"
"    try {\n"
"        $fs = [System.IO.File]::OpenRead($path)\n"
"        try {\n"
"            $buf = New-Object byte[] 4096\n"
"            [void]$fs.Read($buf, 0, 4096)\n"
"            $peOffset = [BitConverter]::ToInt32($buf, 0x3C)\n"
"            $machine = [BitConverter]::ToUInt16($buf, $peOffset + 4)\n"
"            switch ($machine) {\n"
"                0x014c { 'x86' }\n"
"                0x8664 { 'x64' }\n"
"                0xAA64 { 'arm64' }\n"
"                default { 'other' }\n"
"            }\n"
"        } finally { $fs.Close() }\n"
"    } catch { 'error' }\n"
"}\n"
"$installedExe = Join-Path $installDir 'premake5.exe'\n"
"$installedArch = if (Test-Path $installedExe) { Get-PeMachine $installedExe } else { '' }\n"
"if ($installedArch -ne 'x64' -and (Test-Path $installDir)) {\n"
"    Write-Host \"Wiping stale premake install (detected arch='$installedArch', need x64)\"\n"
"    Remove-Item -Recurse -Force $installDir\n"
"}\n"
"if (-not (Test-Path (Join-Path $installDir 'premake5.exe'))) {\n"
"    Write-Host \"Installing vendored premake5.exe to $installDir\"\n"
"    New-Item -ItemType Directory -Force -Path $installDir | Out-Null\n"
"    Copy-Item -Force '${_rive_premake_vendored_native}' (Join-Path $installDir 'premake5.exe')\n"
"    Copy-Item -Force '${_rive_premake_vendored_native}' (Join-Path $installDir 'premake5')\n"
"}\n"
)
    endif()
    file(APPEND "${RIVE_BUILD_WRAPPER}"
"\n"
"# Scrub PLATFORM so rive's bash script doesn't accidentally inherit\n"
"# anything we set during the bootstrap step.\n"
"Remove-Item Env:PLATFORM -ErrorAction SilentlyContinue\n"
"\n"
"# Ensure fxc/msbuild still on PATH for the rive build itself.\n"
"if (-not (Get-Command fxc -ErrorAction SilentlyContinue)) {\n"
"    & '${_rive_setup_ps1_native}'\n"
"}\n"
"\n"
"# Hand off to rive's script.\n"
"& sh '${_rive_build_sh_native}' '${RIVE_CONFIG}' 2>&1\n"
"$riveExit = $LASTEXITCODE\n"
"\n"
"# Diagnostic on failure: re-run premake directly so errors surface\n"
"# (rive's pipe through grep can swallow them).\n"
"if ($riveExit -ne 0) {\n"
"    Write-Host ''\n"
"    Write-Host '=== rive script failed. Re-running premake5 directly for diagnostics ==='\n"
"    $pm = Join-Path $installDir 'premake5.exe'\n"
"    if (Test-Path $pm) {\n"
"        & $pm 'vs2022' \"--config=${RIVE_CONFIG}\" \"--out=out/${RIVE_CONFIG}\" '--with_rive_text' '--with_rive_layout' 2>&1\n"
"        Write-Host \"=== premake5 standalone exit: $LASTEXITCODE ===\"\n"
"    }\n"
"}\n"
"exit $riveExit\n"
)
else()
    set(RIVE_BUILD_WRAPPER "${RIVE_BUILD_DIR}/build_rive_wrapper.sh")
    file(WRITE "${RIVE_BUILD_WRAPPER}"
"#!/bin/bash\n"
"# Auto-generated by cmake/BuildRive.cmake — do not edit.\n"
"set -e\n"
"cd \"${RIVE_BUILD_DIR}\"\n"
"RIVE_OUT=\"out/${RIVE_CONFIG}\"\n"
"if [ -d \"$RIVE_OUT\" ] && [ ! -f \"$RIVE_OUT/.rive_premake_args\" ]; then\n"
"    rm -rf \"$RIVE_OUT\"\n"
"fi\n"
"# Wipe a stale Windows-built premake5.exe left from a shared-FS\n"
"# Windows build — it'd fool rive's bootstrap test into using a PE\n"
"# binary on a Unix host.\n"
"RIVE_PREMAKE_INSTALL=\"${RIVE_RUNTIME_DIR}/build/dependencies/premake-core/bin/v5.0.0-beta7_release\"\n"
"if [ -f \"$RIVE_PREMAKE_INSTALL/premake5.exe\" ] && [ ! -x \"$RIVE_PREMAKE_INSTALL/premake5\" ]; then\n"
"    rm -rf \"${RIVE_RUNTIME_DIR}/build/dependencies/premake-core\"\n"
"fi\n"
"exec \"${RIVE_RUNTIME_DIR}/build/build_rive.sh\" \"${RIVE_CONFIG}\"\n")
    execute_process(COMMAND chmod +x "${RIVE_BUILD_WRAPPER}")
endif()

if(APPLE)
    set(RIVE_BUILD_CMD
        "${CMAKE_COMMAND}" -E env
        "PATH=/usr/bin:/bin:/usr/sbin:/sbin:/Library/Developer/CommandLineTools/usr/bin"
        "${RIVE_BUILD_WRAPPER}"
    )
elseif(WIN32)
    set(RIVE_BUILD_CMD
        powershell -ExecutionPolicy Bypass -NoProfile -File "${RIVE_BUILD_WRAPPER}"
    )
else()
    set(RIVE_BUILD_CMD "${RIVE_BUILD_WRAPPER}")
endif()

# Custom build step. BYPRODUCTS is what lets downstream targets take a file
# dependency on the libs (OUTPUT-only wouldn't, because the wrapper premake
# file is regenerated on every configure).
add_custom_command(
    OUTPUT ${RIVE_ALL_LIBS}
    COMMAND ${RIVE_BUILD_CMD}
    WORKING_DIRECTORY "${RIVE_BUILD_DIR}"
    DEPENDS "${RIVE_PREMAKE_WRAPPER}"
    COMMENT "Building rive-runtime (first build ~30-60s, then incremental)"
    VERBATIM
)

add_custom_target(rive_external DEPENDS ${RIVE_ALL_LIBS})

# Public-facing target. INTERFACE because we don't own any compiled sources
# for it — we just stitch together the upstream-built libs + headers.
add_library(rive INTERFACE)
add_dependencies(rive rive_external)
target_link_libraries(rive INTERFACE ${RIVE_ALL_LIBS})

# Rive's public headers. Internal-to-rive includes (harfbuzz/src,
# sheenbidi/Headers) aren't needed by consumers since rive wraps them.
target_include_directories(rive INTERFACE "${RIVE_RUNTIME_DIR}/include")

# Frameworks rive's Apple font backend (src/text/font_hb_apple.mm) needs.
if(APPLE)
    target_link_libraries(rive INTERFACE
        "-framework Foundation"
        "-framework CoreGraphics"
        "-framework CoreText"
    )
endif()
